version: "3"
services:
  # postgres:
  #   volumes:
  #     - ../persistent-data/private-testnet/postgres:/var/lib/postgresql/data
  stacks-node-follower:
    # image: blockstack/stacks-blockchain:latest
    image: blockstack/stacks-blockchain:feat-miner-control
    # image: blockstack/stacks-blockchain:develop
    volumes:
      # - ../persistent-data/private-testnet/stacks-blockchain:/root/stacks-node/data
      - ./private-testnet:/src/stacks-node
  explorer:
    image: blockstack/explorer:latest
    container_name: explorer
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3999
      - NEXT_PUBLIC_TESTNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3399
      - MOCKNET_API_SERVER=http://localhost:3999
      - TESTNET_API_SERVER=http://localhost:3999
    ports:
      - 3000:3000
    networks:
      - stacks-blockchain
  bitcoin:
    image: blockstack/bitcoind:puppet-chain
    container_name: bitcoin
    restart: on-failure
    volumes:
      # - ../persistent-data/private-testnet/bitcoin:/root/.bitcoin
      - ./private-testnet:/etc/bitcoin
    expose:
      - 18443
      - 28444
    environment:
      - DYNAMIC_GENESIS_TIMESTAMP=1
      - RUST_BACKTRACE=1
    networks:
      - stacks-blockchain
