version: "3.5"
services:
  bitcoin-core:
    build: ${SCRIPTPATH}/Dockerfiles
    container_name: bitcoin-core
    volumes:
      - "${BITCOIN_BLOCKCHAIN_FOLDER}:/root/.bitcoin"
      - "${BITCOIN_CONFIG_FILE}:/etc/bitcoin/bitcoin.conf"
    networks:
      - default