version: "3"
services:
  stacks-proxy:
    image: nginx:alpine
    container_name: stacks-proxy
    restart: on-failure
    ports:
      - ${NGINX_PROXY_PORT:-80}:80
    networks:
      - default
    profiles:
      - stacks-blockchain
    volumes:
      - ${SCRIPTPATH}/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
